name: food_truck
description: A simple food truck locator app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  convert: ^3.0.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  modal_progress_hud_nsn: ^0.2.1
  animated_text_kit: ^4.2.2
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  location: ^4.4.0
  url_launcher: ^6.1.4
  typed_data: ^1.3.1
  firebase_database: ^9.0.16
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: FugazOne
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf